<Project Sdk="Godot.NET.Sdk/4.5.0">
  <ItemGroup>
    <ProjectReference Include="..\FarmDefenseHarvestWars.Shared\FarmDefenseHarvestWars.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Refit" Version="9.0.2" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>